### PR TITLE
More reliable type introspection

### PR DESCRIPTION
**Pull request by ghost**
Hi,

Discovered this via Brisk. 
Discovered Brisk via [ladybug](https://github.com/ethanhuang13/ladybug). 
Discovered ladybug via [this page](https://github.com/dkhamsing/open-source-ios-apps/blob/master/README.md#mastodon).

This repo is a simple idea that might get me using storyboards again! So thanks.

I wanted to make a small, but important change.

There are a few caveats with the following.

```swift
String(describing: )
```

screen shot 2018-08-09 at 16 52 21

So your not always guaranteed to get the class name using this approach.

Have added a utility to more reliable check the type of a class.

```swift
func typeName(_ some: Any) -> String {
    return (some is Any.Type) ? "\(some)" : "\(type(of: some))"
}
```

### CODE REVIEW

**Comment by florianbuerger** [comment]
Hi Rob, I am glad you discovered this repo and thanks for taking the time to submit your PR. 

I don't see why this is necessary though. Did you run into problems? The used initializer will always return the type name for a given class meta type, e.g. `String(describing: UIViewController.self)`.

**Comment by ghost** [comment]
Hello again,

No, not run into problems. 

But the points highlighted here (by the red circle), show that the used initialiser **will not always** return the type name for a given class meta type.

43910596-26eed81e-9bf5-11e8-81e0-4813073ac92e

If one day your class conformed to `CustomStringConvertible` for example...

**Comment by florianbuerger** [comment]
No that doesn't matter. `CustomStringConvertible` is only relevant on instances of that type not on the meta type. And you can't extend a meta type to conform to something like `CustomStringConvertible`.

Example: 

screen shot 2018-08-09 at 3 30 02 pm

**Comment by ghost** [comment]
I did honestly think there was an instance involved at some point in your code. My bad. I'm inclined to agree with you. 

My paranoia about private API's and private implementations would still push me away from using String(describing: ), given that a [metatype is itself an instance](http://www.sealiesoftware.com/blog/archive/2009/04/14/objc_explain_Classes_and_metaclasses.html). 

I can't argue that an instance of a metatype does conform to `CustomStringConvertible` (and returns the string 'Foo'), or that it will one day conform to this protocol.

Thanks for your time bro

**Pull request closed without merging**
